# Generated by Django 6.0.2 on 2026-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ca_emi_calculator',
            name='principal_amount',
        ),
        migrations.RemoveField(
            model_name='ca_emi_calculator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ca_gst_calculator',
            name='gst_percentage',
        ),
        migrations.RemoveField(
            model_name='ca_tds_calculator',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='ca_tds_calculator',
            name='user',
        ),
        migrations.AddField(
            model_name='ca_gst_calculator',
            name='cgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ca_gst_calculator',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ca_gst_calculator',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ca_gst_calculator',
            name='sgst_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='ca_emi_calculator',
            name='monthly_emi',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ca_emi_calculator',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ca_emi_calculator',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='calculation_type',
            field=models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_type',
            field=models.CharField(choices=[('igst', 'IGST'), ('cgst_sgst', 'CGST & SGST')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_tds_calculator',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ca_tds_calculator',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=111, max_digits=12),
            preserve_default=False,
        ),
    ]
