# Generated by Django 6.0.2 on 2026-02-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0006_banking_sip_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingSWPCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_withdrawal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_period_years', models.PositiveIntegerField()),
                ('total_withdrawn', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('final_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
