# Generated by Django 6.0.2 on 2026-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0007_bankingswpcalculator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankingswpcalculator',
            name='final_balance',
        ),
        migrations.AddField(
            model_name='bankingswpcalculator',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankingswpcalculator',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankingswpcalculator',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
