# Generated by Django 6.0.2 on 2026-02-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0008_remove_bankingswpcalculator_final_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankingSWPCalculator',
        ),
        migrations.AddField(
            model_name='ca_gst_calculator',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='calculation_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
