# Generated by Django 6.0.2 on 2026-02-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0009_delete_bankingswpcalculator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='calculation_type',
            field=models.CharField(choices=[('Exclusive', 'Exclusive'), ('Inclusive', 'Inclusive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='cgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_type',
            field=models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST'), ('CGST_SGST', 'CGST + SGST')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='net_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='sgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='total_amount',
            field=models.FloatField(),
        ),
    ]
