# Generated by Django 6.0.2 on 2026-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0010_alter_ca_gst_calculator_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
