# Generated by Django 6.0.2 on 2026-02-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0011_alter_ca_gst_calculator_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_gst_calculator',
            name='gst_type',
            field=models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST'), ('CGST/SGST', 'CGST + SGST')], max_length=20),
        ),
    ]
