# Generated by Django 6.0.2 on 2026-02-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0012_alter_ca_gst_calculator_gst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_emi_calculator',
            name='monthly_emi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_emi_calculator',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_emi_calculator',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ca_emi_calculator',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
