# Generated by Django 6.0.2 on 2026-02-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0013_alter_ca_emi_calculator_monthly_emi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ca_emi_calculator',
            old_name='monthly_emi',
            new_name='emi',
        ),
        migrations.RenameField(
            model_name='ca_emi_calculator',
            old_name='time_period_years',
            new_name='time_in_years',
        ),
        migrations.AddField(
            model_name='ca_emi_calculator',
            name='calculator_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
