# Generated by Django 6.0.2 on 2026-02-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0014_rename_monthly_emi_ca_emi_calculator_emi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingSWPCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_withdrawal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_period_years', models.PositiveIntegerField()),
                ('total_withdrawn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
