# Generated by Django 6.0.2 on 2026-02-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0015_bankingswpcalculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking_sip_calculator',
            name='estimated_return',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banking_sip_calculator',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banking_sip_calculator',
            name='total_invested',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
    ]
