# Generated by Django 6.0.2 on 2026-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0017_banking_fd_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BANKING_PPF_Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_period_years', models.PositiveIntegerField()),
                ('frequency', models.CharField(max_length=10)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estimated_return', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
