# Generated by Django 6.0.2 on 2026-02-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0018_banking_ppf_calculator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BANKING_RD_Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_period_years', models.PositiveIntegerField()),
                ('invested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_return', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
