# Generated by Django 6.0.2 on 2026-02-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0020_rename_time_in_years_ca_emi_calculator_time_period_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca_emi_calculator',
            name='time_period_years',
            field=models.IntegerField(),
        ),
    ]
