# Generated by Django 6.0.2 on 2026-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0022_banking_maturity_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
