# Generated by Django 6.0.2 on 2026-03-05 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0024_landunit_calculator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PAINTCOST_Calculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_type', models.CharField(max_length=100)),
                ('total_area', models.DecimalField(decimal_places=4, max_digits=15)),
                ('area_unit', models.CharField(max_length=50)),
                ('paint_efficiency', models.DecimalField(decimal_places=2, max_digits=10)),
                ('efficiency_unit', models.CharField(max_length=50)),
                ('cost_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paint_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
