# Generated by Django 6.0.2 on 2026-03-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0026_electricitybill_calculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banking_ppf_calculator',
            name='frequency',
            field=models.CharField(max_length=20),
        ),
    ]
