# Generated by Django 6.0.2 on 2026-03-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0029_insurance_emi_calculator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankingswpcalculator',
            old_name='final_amount',
            new_name='total_amount',
        ),
    ]
