# Generated by Django 6.0.2 on 2026-03-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0030_rename_final_amount_bankingswpcalculator_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banking_rd_calculator',
            old_name='monthly_amount',
            new_name='monthly_investment',
        ),
    ]
