# Generated by Django 6.0.2 on 2026-03-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0031_rename_monthly_amount_banking_rd_calculator_monthly_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banking_ppf_calculator',
            old_name='annual_rate',
            new_name='return_rate',
        ),
        migrations.RenameField(
            model_name='banking_ppf_calculator',
            old_name='time_period_years',
            new_name='time_in_years',
        ),
        migrations.RenameField(
            model_name='banking_ppf_calculator',
            old_name='investment',
            new_name='total_investment',
        ),
    ]
