# Generated by Django 6.0.2 on 2026-03-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0032_rename_annual_rate_banking_ppf_calculator_return_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banking_maturity_calculator',
            old_name='annual_rate',
            new_name='rate_of_interest',
        ),
        migrations.RenameField(
            model_name='banking_maturity_calculator',
            old_name='invested_amount',
            new_name='total_investment',
        ),
    ]
