# Generated by Django 6.0.2 on 2026-03-10 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0033_rename_annual_rate_banking_maturity_calculator_rate_of_interest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BANKING_MATURITY_Calculator',
            new_name='INSURANCE_MATURITY_Calculator',
        ),
    ]
