# Generated by Django 6.0.2 on 2026-03-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0034_rename_banking_maturity_calculator_insurance_maturity_calculator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landunit_calculator',
            old_name='total_cost',
            new_name='total_amount',
        ),
    ]
