# Generated by Django 6.0.2 on 2026-03-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0035_rename_total_cost_landunit_calculator_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='landunit_calculator',
            name='entered_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
