# Generated by Django 6.0.2 on 2026-03-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0036_landunit_calculator_entered_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landunit_calculator',
            name='entered_amount',
        ),
    ]
