# Generated by Django 6.0.2 on 2026-03-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0037_remove_landunit_calculator_entered_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paintcost_calculator',
            old_name='total_cost',
            new_name='total_amount',
        ),
    ]
