# Generated by Django 6.0.2 on 2026-03-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0038_rename_total_cost_paintcost_calculator_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricitybill_calculator',
            old_name='total_cost',
            new_name='total_amount',
        ),
    ]
