# Generated by Django 6.0.2 on 2026-03-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca_app', '0040_insurance_irr_calculator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance_irr_calculator',
            old_name='total_investment',
            new_name='initial_investment',
        ),
    ]
